// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64
	Name      string
	Icon      string
	UserID    pgtype.Int8
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Exercise struct {
	ID             int64
	Name           string
	Description    string
	UserID         pgtype.Int8
	DefaultMetrics []byte
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type ExerciseVariation struct {
	ID         int64
	Name       string
	ExerciseID int64
	Metrics    []byte
	Notes      string
}

type Group struct {
	ID          int64
	Name        string
	Description string
	UserID      int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type IntervalExercisePrescription struct {
	ID                  int64
	GroupID             int64
	ExerciseVariationID int64
	PlanIntervalID      int64
	Rpe                 pgtype.Int4
	Sets                int32
	Reps                pgtype.Int4
	Duration            pgtype.Interval
	Rest                pgtype.Interval
}

type IntervalGroupAssignment struct {
	ID             int64
	PlanIntervalID int64
	GroupID        int64
	Frequency      int32
}

type Plan struct {
	ID          int64
	Name        string
	Description string
	UserID      int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PlanInterval struct {
	ID        int64
	PlanID    int64
	Name      pgtype.Text
	Duration  pgtype.Interval
	Order     int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type User struct {
	ID        int64
	Email     string
	FirstName string
	LastName  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
