// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64
	Name      string
	Icon      string
	UserID    pgtype.Int8
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Exercise struct {
	ID          int64
	Name        string
	Description string
	UserID      pgtype.Int8
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type ExerciseVariation struct {
	ID         int64
	ExerciseID int64
	Name       string
}

type ExerciseVariationParam struct {
	ID                  int64
	ExerciseVariationID int64
	ParameterTypeID     int64
	Locked              bool
}

type Group struct {
	ID          int64
	Name        string
	Description string
	UserID      int64
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type IntervalExercisePrescription struct {
	ID                  int64
	GroupID             int64
	ExerciseVariationID int64
	PlanIntervalID      int64
	Rpe                 pgtype.Int4
	Sets                int32
	Reps                pgtype.Int4
	Duration            pgtype.Interval
	SubReps             pgtype.Int4
	SubRepWorkDuration  pgtype.Interval
	SubRepRestDuration  pgtype.Interval
	Rest                pgtype.Interval
}

type IntervalGroupAssignment struct {
	ID             int64
	PlanIntervalID int64
	GroupID        int64
	Frequency      int32
}

type ParameterType struct {
	ID          int64
	Name        string
	DataType    string
	DefaultUnit string
	MinValue    pgtype.Float8
	MaxValue    pgtype.Float8
}

type Plan struct {
	ID          int64
	Name        string
	Description string
	UserID      int64
	IsTemplate  bool
	IsPublic    bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type PlanInterval struct {
	ID          int64
	PlanID      int64
	Name        pgtype.Text
	Description pgtype.Text
	Duration    pgtype.Interval
	Order       int32
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID        int64
	Email     string
	FirstName string
	LastName  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserParameterType struct {
	UserID          int64
	ParameterTypeID int64
}
